version: 2
updates:
- package-ecosystem: gradle
  directory: "/android"
  schedule:
    interval: daily
    time: "21:00"
    timezone: Asia/Calcutta
  open-pull-requests-limit: 50
  ignore:
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
