import { Platform, StatusBar, StyleSheet } from 'react-native';

export const COLORS = {
  dark: {
    bg: '#0f172a',
    cardBg: '#1e293b',
    cardBorder: '#334155',
    inputBg: '#0f172a',
    inputBorder: '#475569',
    text: '#f8fafc',
    textMuted: '#94a3b8',
    textSecondary: '#cbd5e1',
    placeholder: '#64748b',
    primary: '#3b82f6',
    primaryPressed: '#2563eb',
    danger: '#ef4444',
    dangerPressed: '#dc2626',
    badgeActiveBg: '#064e3b',
    badgeActiveText: '#34d399',
    badgeIdleBg: '#334155',
    badgeIdleText: '#94a3b8',
    errorBg: '#450a0a',
    errorBorder: '#991b1b',
    errorText: '#f87171',
    divider: '#334155',
  },
  light: {
    bg: '#f8fafc',
    cardBg: '#ffffff',
    cardBorder: '#e2e8f0',
    inputBg: '#ffffff',
    inputBorder: '#cbd5e1',
    text: '#0f172a',
    textMuted: '#64748b',
    textSecondary: '#334155',
    placeholder: '#94a3b8',
    primary: '#2563eb',
    primaryPressed: '#1d4ed8',
    danger: '#dc2626',
    dangerPressed: '#b91c1c',
    badgeActiveBg: '#dcfce7',
    badgeActiveText: '#15803d',
    badgeIdleBg: '#f1f5f9',
    badgeIdleText: '#64748b',
    errorBg: '#fef2f2',
    errorBorder: '#fecaca',
    errorText: '#dc2626',
    divider: '#e2e8f0',
  },
};

export const getTheme = (isDark: boolean) => (isDark ? COLORS.dark : COLORS.light);

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#0f172a',
  },
  container: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 24) + 12 : 16,
    paddingBottom: 32,
  },
  headerContainer: {
    marginBottom: 16,
    alignItems: 'flex-start',
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#f8fafc',
    letterSpacing: -0.5,
  },
  headerSubtitle: {
    fontSize: 13,
    color: '#94a3b8',
    marginTop: 3,
  },
  card: {
    backgroundColor: '#1e293b',
    borderRadius: 12,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#334155',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  cardTitle: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    color: '#94a3b8',
    marginBottom: 12,
  },
  inputGroup: {
    marginBottom: 12,
  },
  inputLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#cbd5e1',
    marginBottom: 6,
  },
  textInput: {
    backgroundColor: '#0f172a',
    borderWidth: 1,
    borderColor: '#475569',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: '#f8fafc',
  },
  switchOverView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
  },
  switchText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#f8fafc',
    flex: 1,
    paddingRight: 8,
  },
  switchSwitch: {
    alignItems: 'flex-end',
  },
  divider: {
    height: 1,
    backgroundColor: '#334155',
    marginVertical: 4,
  },
  pickerOverView: {
    paddingVertical: 8,
  },
  pickerLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  pickerText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#f8fafc',
  },
  pickerPicker: {
    backgroundColor: '#0f172a',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#475569',
    overflow: 'hidden',
  },
  pickerItem: {
    color: '#f8fafc',
    fontSize: 14,
  },
  statusCard: {
    backgroundColor: '#1e293b',
    borderRadius: 12,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#334155',
    alignItems: 'center',
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 12,
    marginLeft: 8,
  },
  statusBadgeActive: {
    backgroundColor: '#064e3b',
  },
  statusBadgeIdle: {
    backgroundColor: '#334155',
  },
  statusBadgeText: {
    fontSize: 12,
    fontWeight: '700',
  },
  statusBadgeTextActive: {
    color: '#34d399',
  },
  statusBadgeTextIdle: {
    color: '#94a3b8',
  },
  statusLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#cbd5e1',
  },
  lastCheckedText: {
    fontSize: 13,
    color: '#94a3b8',
    marginBottom: 4,
    textAlign: 'center',
  },
  errorContainer: {
    backgroundColor: '#450a0a',
    borderColor: '#991b1b',
    borderWidth: 1,
    borderRadius: 8,
    padding: 10,
    marginBottom: 12,
  },
  errorText: {
    color: '#f87171',
    fontSize: 13,
    textAlign: 'center',
    fontWeight: '500',
  },
  buttonContainer: {
    marginTop: 6,
    borderRadius: 10,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 3,
  },
  actionButton: {
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 3,
  },
  buttonStart: {
    backgroundColor: '#2563eb',
  },
  buttonStop: {
    backgroundColor: '#dc2626',
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  loadingContainer: {
    marginTop: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  webviewCard: {
    backgroundColor: '#1e293b',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#334155',
    overflow: 'hidden',
    marginTop: 14,
    height: 380,
  },
  webviewHeader: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: '#0f172a',
    borderBottomWidth: 1,
    borderBottomColor: '#334155',
  },
  webviewHeaderText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#94a3b8',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  webview: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
});

export default styles;
